package com.termux.app.madmax.ai.engine;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.termux.app.madmax.ai.model.AICommandExplanation;
import com.termux.app.madmax.ai.model.AICommandGeneration;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Built-in, high-performance offline Command Intelligence engine.
 * Provides deep knowledge for 70+ standard Linux, Termux, and Developer CLI utilities.
 */
public class OfflineCommandIntelligence {

    private static final Map<String, CommandMetadata> COMMAND_DB = new HashMap<>();

    static {
        // --- System & Process Management ---
        register("ps", "Report a snapshot of current running processes.",
            mapOf("-e", "Select all processes.", "-f", "Full-format listing.", "-u", "Select by effective user ID.", "aux", "BSD syntax: show all processes with user and CPU/memory stats."),
            listOf("ps aux", "ps -ef | grep python"), AICommandExplanation.RiskLevel.SAFE);

        register("kill", "Send a termination signal to a process by PID.",
            mapOf("-9", "SIGKILL: force immediate kill (cannot be caught).", "-15", "SIGTERM: graceful termination request.", "-l", "List available signal names."),
            listOf("kill 1234", "kill -9 $(lsof -t -i:8080)"), AICommandExplanation.RiskLevel.CAUTION);

        register("pkill", "Signal processes based on target name or regex pattern.",
            mapOf("-9", "Force kill matching processes.", "-f", "Match against full command line arguments.", "-u", "Match only specific user processes."),
            listOf("pkill node", "pkill -f 'python main.py'"), AICommandExplanation.RiskLevel.CAUTION);

        register("killall", "Kill processes by exact binary name.",
            mapOf("-9", "Force kill immediately with SIGKILL.", "-i", "Ask for confirmation before killing each process.", "-v", "Report if signal was successfully sent."),
            listOf("killall -9 node", "killall python3"), AICommandExplanation.RiskLevel.CAUTION);

        register("htop", "Interactive real-time process viewer and system resource monitor.",
            mapOf("-d", "Update interval in tenths of seconds.", "-u", "Filter by specific username."),
            listOf("htop", "htop -u root"), AICommandExplanation.RiskLevel.SAFE);

        register("top", "Display real-time dynamic view of system processes.",
            mapOf("-n", "Number of iterations before exiting.", "-d", "Delay time between screen updates in seconds."),
            listOf("top", "top -n 5"), AICommandExplanation.RiskLevel.SAFE);

        register("df", "Report file system disk space usage.",
            mapOf("-h", "Human-readable format (MB, GB).", "-T", "Print filesystem type.", "-i", "List inode usage."),
            listOf("df -h", "df -Th"), AICommandExplanation.RiskLevel.SAFE);

        register("du", "Estimate file and directory space usage.",
            mapOf("-h", "Human-readable format.", "-s", "Display total summary only.", "-d", "Max directory depth (e.g. -d 1).", "-a", "Include files in listing."),
            listOf("du -sh *", "du -h -d 1 . | sort -hr"), AICommandExplanation.RiskLevel.SAFE);

        register("free", "Display total amount of free and used physical memory and swap.",
            mapOf("-h", "Human-readable output (GB, MB).", "-m", "Show output in megabytes.", "-s", "Continuously refresh every N seconds."),
            listOf("free -h", "free -m"), AICommandExplanation.RiskLevel.SAFE);

        register("lsof", "List open files, processes, and active network connections.",
            mapOf("-i", "Select network files by protocol or port (e.g. -i:8080).", "-p", "Filter by process PID.", "-t", "Terse output printing only PIDs."),
            listOf("lsof -i :8080", "lsof -i tcp:3000", "lsof -p 1234"), AICommandExplanation.RiskLevel.SAFE);

        register("strace", "Trace system calls and signals generated by an executable.",
            mapOf("-p", "Attach to running process ID.", "-f", "Trace child processes created by fork.", "-e", "Filter specific system calls (e.g. -e open,read).", "-o", "Write trace log to file."),
            listOf("strace -f ./binary", "strace -p 1234 -e trace=network"), AICommandExplanation.RiskLevel.CAUTION);

        register("uname", "Print system, kernel, and hardware architecture information.",
            mapOf("-a", "Print all system info in single line.", "-m", "Print machine hardware architecture.", "-r", "Print kernel release."),
            listOf("uname -a", "uname -m"), AICommandExplanation.RiskLevel.SAFE);

        register("uptime", "Tell how long the system has been running and load averages.",
            mapOf("-p", "Pretty print duration format.", "-s", "Print system up since date/time."),
            listOf("uptime", "uptime -p"), AICommandExplanation.RiskLevel.SAFE);

        register("whoami", "Print the effective user ID / username.",
            mapOf(),
            listOf("whoami"), AICommandExplanation.RiskLevel.SAFE);

        register("date", "Display or format the current date and time.",
            mapOf("-u", "Display UTC/GMT time.", "+%s", "Format as Unix timestamp in seconds."),
            listOf("date", "date -u", "date +%Y-%m-%d"), AICommandExplanation.RiskLevel.SAFE);

        register("which", "Locate the executable path of a command in $PATH.",
            mapOf("-a", "Print all matching pathnames of each argument."),
            listOf("which bash", "which python3"), AICommandExplanation.RiskLevel.SAFE);

        // --- File & Directory Operations ---
        register("ls", "List directory contents.",
            mapOf("-l", "Long format showing permissions, owner, size, date.", "-a", "Include hidden entries (starting with .).", "-h", "Human readable sizes.", "-t", "Sort by modification time (newest first).", "-R", "Recursively list subdirectories."),
            listOf("ls -la", "ls -lh", "ls -lhtr"), AICommandExplanation.RiskLevel.SAFE);

        register("rm", "Remove files or directories.",
            mapOf("-r", "Recursive removal of directories and contents.", "-f", "Force removal without prompt, ignore nonexistent files.", "-i", "Prompt interactively before every removal.", "-v", "Verbose output."),
            listOf("rm file.txt", "rm -rf build/"), AICommandExplanation.RiskLevel.CAUTION);

        register("cp", "Copy files and directories.",
            mapOf("-r", "Recursive copy for directories.", "-p", "Preserve file attributes, timestamps, and permissions.", "-v", "Verbose progress.", "-u", "Copy only when source is newer than destination."),
            listOf("cp file.txt backup.txt", "cp -rp src/ /backup/"), AICommandExplanation.RiskLevel.SAFE);

        register("mv", "Move or rename files and directories.",
            mapOf("-f", "Force overwrite of target.", "-i", "Interactive prompt before overwrite.", "-u", "Update only when source is newer."),
            listOf("mv old_name.txt new_name.txt", "mv *.log /archive/"), AICommandExplanation.RiskLevel.SAFE);

        register("mkdir", "Create directories.",
            mapOf("-p", "Create parent directories as needed without error.", "-v", "Print message for each created directory.", "-m", "Set file mode/permissions."),
            listOf("mkdir -p src/main/java", "mkdir new_folder"), AICommandExplanation.RiskLevel.SAFE);

        register("rmdir", "Remove empty directories.",
            mapOf("-p", "Remove directory and its ancestor parents if empty."),
            listOf("rmdir empty_dir", "rmdir -p a/b/c"), AICommandExplanation.RiskLevel.SAFE);

        register("touch", "Change file timestamps or create empty file.",
            mapOf("-a", "Change only access time.", "-m", "Change only modification time.", "-c", "Do not create new file if nonexistent."),
            listOf("touch newfile.txt", "touch -m existing.txt"), AICommandExplanation.RiskLevel.SAFE);

        register("chmod", "Change file access permissions and modes.",
            mapOf("+x", "Grant execute permission.", "755", "Owner rwx, Group/Others rx (standard binary/script).", "644", "Owner rw, Group/Others r (standard file).", "-R", "Apply permissions recursively."),
            listOf("chmod +x script.sh", "chmod -R 755 bin/"), AICommandExplanation.RiskLevel.CAUTION);

        register("chown", "Change file owner and group.",
            mapOf("-R", "Operate on files and directories recursively.", "-v", "Verbose diagnostic output."),
            listOf("chown user:group file.txt", "chown -R user /var/www"), AICommandExplanation.RiskLevel.CAUTION);

        register("find", "Search for files in a directory hierarchy in real-time.",
            mapOf("-name", "File pattern match (case-sensitive).", "-iname", "Case-insensitive file pattern match.", "-type", "File type: f (file), d (directory), l (symlink).", "-size", "Size filter (e.g. +50M, -10k).", "-mtime", "Modified days ago (+7, -1).", "-exec", "Execute command on each match."),
            listOf("find . -name '*.java'", "find / -size +100M", "find . -type f -name '*.log' -delete"), AICommandExplanation.RiskLevel.SAFE);

        // --- Archive & Compression ---
        register("tar", "Archive utility for creating and extracting tarballs (.tar, .tar.gz, .tar.xz).",
            mapOf("-c", "Create new archive.", "-x", "Extract archive contents.", "-v", "Verbosely list processed files.", "-f", "Specify archive filename.", "-z", "Gzip compression/decompression.", "-J", "XZ compression/decompression."),
            listOf("tar -czvf archive.tar.gz folder/", "tar -xzvf archive.tar.gz", "tar -xvf archive.tar.xz"), AICommandExplanation.RiskLevel.SAFE);

        register("gzip", "Compress files using Lempel-Ziv coding (LZ77).",
            mapOf("-d", "Decompress file.", "-k", "Keep input files unchanged.", "-9", "Maximum compression level."),
            listOf("gzip -k file.txt", "gzip -d file.txt.gz"), AICommandExplanation.RiskLevel.SAFE);

        register("gunzip", "Decompress gzip archives.",
            mapOf("-k", "Keep input files unchanged.", "-f", "Force overwrite of output files."),
            listOf("gunzip archive.gz"), AICommandExplanation.RiskLevel.SAFE);

        register("zip", "Package and compress files into a ZIP archive.",
            mapOf("-r", "Recurse into directories.", "-e", "Encrypt archive with password prompt.", "-9", "Compress better (maximum level)."),
            listOf("zip -r archive.zip folder/", "zip file.zip file.txt"), AICommandExplanation.RiskLevel.SAFE);

        register("unzip", "List, test and extract compressed files in a ZIP archive.",
            mapOf("-l", "List archive contents without extracting.", "-d", "Extract files into specified destination directory.", "-q", "Quiet mode."),
            listOf("unzip archive.zip", "unzip -l archive.zip", "unzip archive.zip -d /target/"), AICommandExplanation.RiskLevel.SAFE);

        // --- Text & Stream Processing ---
        register("cat", "Concatenate files and print on the standard output.",
            mapOf("-n", "Number all output lines.", "-b", "Number nonempty output lines.", "-s", "Suppress repeated empty output lines."),
            listOf("cat file.txt", "cat -n script.sh"), AICommandExplanation.RiskLevel.SAFE);

        register("head", "Output the first part of files.",
            mapOf("-n", "Print the first N lines (default 10).", "-c", "Print the first N bytes."),
            listOf("head -n 20 file.txt", "head -n 50 log.txt"), AICommandExplanation.RiskLevel.SAFE);

        register("tail", "Output the last part of files.",
            mapOf("-n", "Output the last N lines.", "-f", "Follow output in real time as file grows.", "-s", "Sleep interval between checks."),
            listOf("tail -n 20 file.txt", "tail -f app.log"), AICommandExplanation.RiskLevel.SAFE);

        register("less", "View file contents with bidirectional scrolling.",
            mapOf("-N", "Show line numbers.", "-S", "Chop long lines instead of wrapping.", "-i", "Ignore case in searches."),
            listOf("less file.txt", "less -N output.log"), AICommandExplanation.RiskLevel.SAFE);

        register("echo", "Display a line of text / print string to stdout.",
            mapOf("-n", "Do not output trailing newline.", "-e", "Enable interpretation of backslash escapes (\\n, \\t)."),
            listOf("echo 'Hello World'", "echo -e 'Line 1\\nLine 2'"), AICommandExplanation.RiskLevel.SAFE);

        register("printf", "Format and print data using format specifiers.",
            mapOf(),
            listOf("printf '%s: %d\\n' 'Count' 42"), AICommandExplanation.RiskLevel.SAFE);

        register("tee", "Read from stdin and write to stdout and files simultaneously.",
            mapOf("-a", "Append to given files, do not overwrite.", "-i", "Ignore interrupt signals."),
            listOf("make 2>&1 | tee build.log", "echo 'text' | tee -a log.txt"), AICommandExplanation.RiskLevel.SAFE);

        register("grep", "Search text using regular expressions.",
            mapOf("-r", "Recursive search in directories.", "-n", "Prefix line numbers to output.", "-i", "Case-insensitive matching.", "-v", "Invert match (select non-matching lines).", "-E", "Extended regular expressions.", "-l", "Print only filenames of matching files."),
            listOf("grep -rn 'MainActivity' .", "grep -i 'error' app.log", "grep -v '^#' config.conf"), AICommandExplanation.RiskLevel.SAFE);

        register("sed", "Stream editor for filtering and transforming text.",
            mapOf("-i", "Edit files in-place.", "-e", "Script/expression to execute.", "-E", "Use extended regular expressions."),
            listOf("sed -i 's/old/new/g' file.txt", "sed -n '1,10p' file.txt"), AICommandExplanation.RiskLevel.CAUTION);

        register("awk", "Pattern scanning and text processing language.",
            mapOf("-F", "Define input field separator (e.g. -F: or -F,).", "-v", "Assign variable before program execution."),
            listOf("awk '{print $1, $3}' file.txt", "awk -F: '{print $1}' /etc/passwd"), AICommandExplanation.RiskLevel.SAFE);

        register("jq", "Command-line JSON processor and query filter.",
            mapOf("-r", "Raw output without quotes.", "-C", "Colorize JSON output.", "-s", "Read entire input stream into array."),
            listOf("cat data.json | jq .", "curl -s api.github.com | jq -r '.name'"), AICommandExplanation.RiskLevel.SAFE);

        register("wc", "Print newline, word, and byte counts for files.",
            mapOf("-l", "Print newline/line counts.", "-w", "Print word counts.", "-c", "Print byte counts.", "-m", "Print character counts."),
            listOf("wc -l file.txt", "git status --porcelain | wc -l"), AICommandExplanation.RiskLevel.SAFE);

        register("sort", "Sort lines of text files.",
            mapOf("-n", "Compare according to string numerical value.", "-r", "Reverse sorting order.", "-u", "Output only unique lines.", "-k", "Sort key definition.", "-h", "Human-numeric sort."),
            listOf("sort file.txt", "sort -nr scores.txt", "sort -u list.txt"), AICommandExplanation.RiskLevel.SAFE);

        register("uniq", "Report or omit repeated lines.",
            mapOf("-c", "Prefix lines by number of occurrences.", "-d", "Only print duplicate lines.", "-u", "Only print unique lines.", "-i", "Ignore differences in case."),
            listOf("sort file.txt | uniq -c", "uniq -d duplicates.txt"), AICommandExplanation.RiskLevel.SAFE);

        register("cut", "Remove sections from each line of files.",
            mapOf("-d", "Use custom delimiter instead of TAB.", "-f", "Select only these fields/columns.", "-c", "Select only these character positions."),
            listOf("cut -d: -f1 /etc/passwd", "cut -c 1-10 file.txt"), AICommandExplanation.RiskLevel.SAFE);

        register("xargs", "Build and execute command lines from standard input.",
            mapOf("-I", "Replace string in initial-args.", "-n", "Max arguments per command line.", "-P", "Run up to max-procs concurrently.", "-0", "Input items terminated by null character."),
            listOf("find . -name '*.log' | xargs rm", "cat urls.txt | xargs -n 1 -P 4 curl -O"), AICommandExplanation.RiskLevel.CAUTION);

        register("watch", "Execute a program periodically, showing full-screen output.",
            mapOf("-n", "Specify update interval in seconds (default 2s).", "-d", "Highlight differences between successive updates."),
            listOf("watch -n 1 'df -h'", "watch -d 'ps aux | grep node'"), AICommandExplanation.RiskLevel.SAFE);

        // --- Networking & Remote ---
        register("curl", "Transfer data from or to a server using supported protocols (HTTP, HTTPS, FTP, etc.).",
            mapOf("-s", "Silent mode (suppress progress meter).", "-L", "Follow HTTP 3xx redirects.", "-o", "Write output to specified file.", "-O", "Write output to local file named like remote file.", "-X", "Specify HTTP request method (POST, GET, PUT).", "-H", "Custom header to include in request.", "-d", "HTTP POST data payload."),
            listOf("curl -sL https://api.github.com", "curl -O https://example.com/file.zip", "curl -X POST -H 'Content-Type: application/json' -d '{\"k\":\"v\"}' http://localhost:8080"), AICommandExplanation.RiskLevel.SAFE);

        register("wget", "Non-interactive network downloader.",
            mapOf("-O", "Write documents to file.", "-c", "Resume partially downloaded file.", "-q", "Quiet mode (turn off output).", "-r", "Recursive download."),
            listOf("wget https://example.com/file.zip", "wget -c https://example.com/large.iso"), AICommandExplanation.RiskLevel.SAFE);

        register("ssh", "OpenSSH SSH client for secure remote terminal login.",
            mapOf("-p", "Port to connect to on the remote host.", "-i", "Identity file (private key) for public key authentication.", "-L", "Local port forwarding [bind_address:]port:host:hostport.", "-R", "Remote port forwarding [bind_address:]port:host:hostport.", "-D", "Dynamic application-level port forwarding (SOCKS proxy).", "-N", "Do not execute remote command (useful for port forwarding)."),
            listOf("ssh user@example.com", "ssh -i ~/.ssh/id_rsa -p 2222 user@server.com", "ssh -L 8080:localhost:8080 -N user@remote"), AICommandExplanation.RiskLevel.SAFE);

        register("scp", "Secure copy: copy files between network hosts via SSH.",
            mapOf("-r", "Recursively copy entire directories.", "-P", "Port to connect to on remote host.", "-i", "Identity file for private key authentication."),
            listOf("scp file.txt user@server:/path/", "scp -r user@server:/remote/dir local/"), AICommandExplanation.RiskLevel.SAFE);

        register("rsync", "Fast, versatile, remote and local file-copying and synchronization tool.",
            mapOf("-a", "Archive mode: preserve symlinks, permissions, times, owner.", "-v", "Verbose output.", "-z", "Compress file data during transfer.", "-P", "Keep partial files and show progress.", "--delete", "Delete extraneous files from destination."),
            listOf("rsync -avzP src/ dest/", "rsync -avzP -e 'ssh -p 2222' src/ user@server:/backup/"), AICommandExplanation.RiskLevel.SAFE);

        register("ping", "Send ICMP ECHO_REQUEST packets to network hosts.",
            mapOf("-c", "Stop after sending count packets.", "-i", "Wait interval seconds between sending packets.", "-W", "Time to wait for response in seconds."),
            listOf("ping -c 4 1.1.1.1", "ping -c 4 google.com"), AICommandExplanation.RiskLevel.SAFE);

        register("traceroute", "Print route packets take to network host.",
            mapOf("-n", "Print hop addresses numerically rather than resolving DNS.", "-m", "Max number of hops (default 30)."),
            listOf("traceroute 1.1.1.1", "traceroute -n google.com"), AICommandExplanation.RiskLevel.SAFE);

        register("netstat", "Print network connections, routing tables, and interface statistics.",
            mapOf("-t", "Show TCP ports.", "-u", "Show UDP ports.", "-l", "Show only listening sockets.", "-n", "Show numerical addresses and ports.", "-p", "Show PID and program name owning socket."),
            listOf("netstat -tulnp", "netstat -an | grep 8080"), AICommandExplanation.RiskLevel.SAFE);

        register("ss", "Investigate network sockets (modern replacement for netstat).",
            mapOf("-t", "Display TCP sockets.", "-u", "Display UDP sockets.", "-l", "Display listening sockets.", "-n", "Numeric addresses and ports.", "-p", "Show process using socket."),
            listOf("ss -tulnp", "ss -t state established"), AICommandExplanation.RiskLevel.SAFE);

        register("nc", "Netcat: versatile network utility for reading and writing data across TCP/UDP.",
            mapOf("-l", "Listen mode for inbound connections.", "-p", "Specify local port.", "-v", "Verbose output.", "-z", "Zero-I/O mode (port scan)."),
            listOf("nc -zv 127.0.0.1 8080", "nc -l -p 9000"), AICommandExplanation.RiskLevel.SAFE);

        register("nmap", "Network exploration tool and security / port scanner.",
            mapOf("-p", "Specify port range (e.g. -p 1-1000).", "-sV", "Probe open ports for service/version info.", "-sS", "TCP SYN stealth scan.", "-A", "Aggressive scan with OS detection and traceroute."),
            listOf("nmap 192.168.1.1", "nmap -p 80,443,8080 localhost", "nmap -sV -p 22 192.168.1.50"), AICommandExplanation.RiskLevel.SAFE);

        // --- Compilers, Runtimes & Build Tools ---
        register("clang", "C/C++ compiler frontend based on LLVM.",
            mapOf("-o", "Write executable output to file.", "-Wall", "Enable all common compiler warnings.", "-O2", "Apply level 2 optimizations.", "-g", "Generate debugging symbols.", "-c", "Compile without linking."),
            listOf("clang main.c -o app", "clang -Wall -O2 main.c -o app"), AICommandExplanation.RiskLevel.SAFE);

        register("gcc", "GNU project C and C++ compiler.",
            mapOf("-o", "Specify output binary name.", "-Wall", "Enable all compiler warnings.", "-O3", "Aggressive optimizations.", "-g", "Include debug symbols."),
            listOf("gcc main.c -o app", "gcc -Wall main.c -o app"), AICommandExplanation.RiskLevel.SAFE);

        register("make", "GNU make build automation tool for compiling targets defined in Makefile.",
            mapOf("-j", "Specify number of parallel jobs.", "-f", "Specify custom Makefile.", "-C", "Change directory before reading Makefiles.", "clean", "Standard target to delete compiled artifacts."),
            listOf("make -j4", "make clean", "make -C src/"), AICommandExplanation.RiskLevel.SAFE);

        register("cmake", "Cross-platform build system generator.",
            mapOf("-B", "Specify build directory.", "-S", "Specify source directory.", "--build", "Build project binary tree.", "-D", "Set CMake cache variable."),
            listOf("cmake -B build -S .", "cmake --build build -j4"), AICommandExplanation.RiskLevel.SAFE);

        register("python", "Python programming language interpreter.",
            mapOf("-m", "Run library module as a script (e.g. venv, pip, http.server).", "-c", "Execute program passed as string.", "-v", "Verbose module loading."),
            listOf("python main.py", "python -m http.server 8000", "python -m venv venv"), AICommandExplanation.RiskLevel.SAFE);

        register("python3", "Python 3 interpreter.",
            mapOf("-m", "Run library module as script.", "-c", "Execute command string.", "-u", "Force unbuffered stdout/stderr."),
            listOf("python3 main.py", "python3 -m pip install requests"), AICommandExplanation.RiskLevel.SAFE);

        register("pip", "Package installer for Python.",
            mapOf("install", "Install package(s).", "uninstall", "Remove package(s).", "list", "List installed packages.", "freeze", "Output installed packages in requirements.txt format.", "-r", "Install packages listed in requirements file."),
            listOf("pip install requests", "pip freeze > requirements.txt", "pip install -r requirements.txt"), AICommandExplanation.RiskLevel.SAFE);

        register("node", "Node.js JavaScript server runtime.",
            mapOf("-e", "Evaluate inline JavaScript string.", "-v", "Print node version.", "--watch", "Auto-restart process on file modification."),
            listOf("node server.js", "node -e 'console.log(Date.now())'"), AICommandExplanation.RiskLevel.SAFE);

        register("npm", "Node.js package manager.",
            mapOf("install", "Install package or project dependencies.", "run", "Run script defined in package.json.", "test", "Run test script.", "init", "Create new package.json.", "-g", "Install globally."),
            listOf("npm install", "npm run dev", "npm install -g typescript"), AICommandExplanation.RiskLevel.SAFE);

        register("cargo", "Rust package manager and compiler runner.",
            mapOf("build", "Compile the current package.", "run", "Compile and run binary.", "test", "Execute unit and integration tests.", "check", "Fast syntax and type checking without producing binary.", "--release", "Build optimized release artifacts."),
            listOf("cargo build", "cargo run", "cargo check", "cargo build --release"), AICommandExplanation.RiskLevel.SAFE);

        register("rustc", "The Rust programming language compiler.",
            mapOf("-o", "Write output binary to file.", "-O", "Optimize generated machine code.", "--edition", "Specify Rust edition (2018, 2021)."),
            listOf("rustc main.rs -o app", "rustc -O main.rs"), AICommandExplanation.RiskLevel.SAFE);

        register("gh", "Official GitHub CLI tool.",
            mapOf("auth", "Authenticate and check login status.", "repo", "Clone, create, view repositories.", "pr", "Create, checkout, and review pull requests.", "issue", "List, view, and comment on issues.", "release", "Manage GitHub releases and upload assets."),
            listOf("gh auth status", "gh repo clone user/repo", "gh pr list", "gh pr checkout 42"), AICommandExplanation.RiskLevel.SAFE);

        register("ffmpeg", "Hyper fast audio and video transcoder and stream processor.",
            mapOf("-i", "Specify input file URL or path.", "-c:v", "Video codec (e.g. libx264, copy).", "-c:a", "Audio codec (e.g. aac, copy).", "-crf", "Constant Rate Factor quality parameter (0-51).", "-vn", "Disable video stream recording.", "-y", "Overwrite output files without asking."),
            listOf("ffmpeg -i input.mp4 -c:v libx264 -crf 23 output.mp4", "ffmpeg -i video.mp4 -vn -c:a aac audio.m4a"), AICommandExplanation.RiskLevel.SAFE);

        // --- Git & Development ---
        register("git", "Distributed version control system.",
            mapOf("status", "Show working tree status.", "clone", "Clone a repository into a new directory.", "pull", "Fetch from and integrate with another repository or local branch.", "push", "Update remote refs along with associated objects.", "commit", "Record changes to the repository.", "checkout", "Switch branches or restore working tree files.", "stash", "Stash changes in a dirty working directory.", "log", "Show commit logs.", "diff", "Show changes between commits, commit and working tree.", "rebase", "Reapply commits on top of another base tip."),
            listOf("git status", "git commit -m 'feat: my feature'", "git pull origin main", "git push origin dev"), AICommandExplanation.RiskLevel.SAFE);

        register("pkg", "Termux package management utility (wraps apt with Termux mirrors).",
            mapOf("install", "Install package(s).", "uninstall", "Remove package(s).", "update", "Update package lists from repositories.", "upgrade", "Upgrade all installed packages to latest versions.", "search", "Search for available packages by keyword.", "show", "Show details about package."),
            listOf("pkg update && pkg upgrade", "pkg install git python nodejs", "pkg search rust"), AICommandExplanation.RiskLevel.SAFE);

        register("apt", "Debian package management tool.",
            mapOf("install", "Install package.", "remove", "Remove package.", "update", "Download package lists.", "upgrade", "Upgrade packages."),
            listOf("apt update", "apt install curl"), AICommandExplanation.RiskLevel.SAFE);

        register("docker", "Pack, ship and run any application as a lightweight container.",
            mapOf("ps", "List containers (-a for all).", "run", "Run a command in a new container.", "stop", "Stop running container.", "rm", "Remove container.", "images", "List local images.", "prune", "Remove unused data (-a for all unused images)."),
            listOf("docker ps -a", "docker run -d -p 80:80 nginx", "docker system prune -af"), AICommandExplanation.RiskLevel.SAFE);

        register("tmux", "Terminal multiplexer allowing multiple virtual terminals in a single window.",
            mapOf("new", "Create new session (-s name).", "attach", "Attach to existing session (-t name).", "ls", "List active sessions.", "kill-session", "Kill specific session (-t name)."),
            listOf("tmux", "tmux new -s dev", "tmux attach -t dev", "tmux ls"), AICommandExplanation.RiskLevel.SAFE);

        // --- Termux Specific Utilities ---
        register("termux-setup-storage", "Request Android shared storage permissions and create ~/storage symlinks.",
            mapOf(),
            listOf("termux-setup-storage"), AICommandExplanation.RiskLevel.SAFE);

        register("termux-open", "Open a file or URL with default Android viewer intent.",
            mapOf("-s", "Send intent instead of view.", "--choose", "Always display Android application chooser dialog."),
            listOf("termux-open document.pdf", "termux-open https://github.com"), AICommandExplanation.RiskLevel.SAFE);

        register("termux-clipboard-get", "Retrieve current Android system clipboard content to stdout.",
            mapOf(),
            listOf("termux-clipboard-get", "termux-clipboard-get > clip.txt"), AICommandExplanation.RiskLevel.SAFE);

        register("termux-clipboard-set", "Set Android system clipboard content from arguments or stdin.",
            mapOf(),
            listOf("termux-clipboard-set 'Hello from Termux'", "cat token.txt | termux-clipboard-set"), AICommandExplanation.RiskLevel.SAFE);

        register("termux-notification", "Display an Android system notification from terminal.",
            mapOf("-t", "Title of notification.", "-c", "Content text of notification.", "--priority", "Notification priority (high, low, max, min, default)."),
            listOf("termux-notification -t 'Build Finished' -c 'APKs compiled successfully'"), AICommandExplanation.RiskLevel.SAFE);

        register("termux-toast", "Display a short Android popup toast message.",
            mapOf("-s", "Short duration display.", "-b", "Background color (hex/color name).", "-c", "Text color."),
            listOf("termux-toast 'Operation Complete'", "termux-toast -s 'Done'"), AICommandExplanation.RiskLevel.SAFE);

        register("termux-info", "Print complete diagnostic information about Termux environment and device.",
            mapOf(),
            listOf("termux-info"), AICommandExplanation.RiskLevel.SAFE);

        register("termux-reload-settings", "Reload configuration from ~/.termux/termux.properties.",
            mapOf(),
            listOf("termux-reload-settings"), AICommandExplanation.RiskLevel.SAFE);
    }

    private static void register(String binary, String summary, Map<String, String> flags, List<String> examples, AICommandExplanation.RiskLevel defaultRisk) {
        COMMAND_DB.put(binary, new CommandMetadata(binary, summary, flags, examples, defaultRisk));
    }

    private static Map<String, String> mapOf(String... kvs) {
        Map<String, String> map = new LinkedHashMap<>();
        for (int i = 0; i < kvs.length; i += 2) {
            if (i + 1 < kvs.length) {
                map.put(kvs[i], kvs[i + 1]);
            }
        }
        return map;
    }

    private static List<String> listOf(String... items) {
        return new ArrayList<>(Arrays.asList(items));
    }

    /**
     * Decomposes and explains a shell command.
     */
    @NonNull
    public static AICommandExplanation explainCommand(@NonNull String rawCommand) {
        String trimmed = rawCommand.trim();
        if (trimmed.isEmpty()) {
            return new AICommandExplanation("", "Unknown", "Empty command provided.", null, null, AICommandExplanation.RiskLevel.SAFE, null);
        }

        // Check for destructive commands first
        String dangerWarning = evaluateDestructiveRisk(trimmed);
        boolean isDestructive = dangerWarning != null;

        String[] tokens = trimmed.split("\\s+");
        String binary = tokens[0];
        // Handle sudo / env prefixes
        int binaryIdx = 0;
        if ((binary.equals("sudo") || binary.equals("su") || binary.equals("doas")) && tokens.length > 1) {
            binaryIdx = 1;
            binary = tokens[1];
        }

        CommandMetadata meta = COMMAND_DB.get(binary.toLowerCase(Locale.ROOT));
        Map<String, String> activeFlags = new LinkedHashMap<>();
        List<String> examples = meta != null ? meta.mExamples : Collections.emptyList();
        String summary = meta != null ? meta.mSummary : "Standard Linux executable command: " + binary;
        AICommandExplanation.RiskLevel risk = isDestructive ? AICommandExplanation.RiskLevel.DESTRUCTIVE : (meta != null ? meta.mDefaultRisk : AICommandExplanation.RiskLevel.SAFE);

        if (meta != null) {
            for (int i = binaryIdx + 1; i < tokens.length; i++) {
                String token = tokens[i];
                if (meta.mFlags.containsKey(token)) {
                    activeFlags.put(token, meta.mFlags.get(token));
                } else if (token.startsWith("-") && !token.startsWith("--") && token.length() > 2) {
                    // Split combined single-letter flags (e.g. -la -> -l, -a)
                    for (int c = 1; c < token.length(); c++) {
                        String singleFlag = "-" + token.charAt(c);
                        if (meta.mFlags.containsKey(singleFlag)) {
                            activeFlags.put(singleFlag, meta.mFlags.get(singleFlag));
                        }
                    }
                }
            }
        }

        return new AICommandExplanation(trimmed, binary, summary, activeFlags, examples, risk, dangerWarning);
    }

    /**
     * Generates a shell command from natural language prompt.
     */
    @NonNull
    public static AICommandGeneration generateCommand(@NonNull String prompt) {
        String p = prompt.toLowerCase(Locale.ROOT).trim();

        if (p.contains("storage") && (p.contains("setup") || p.contains("permission") || p.contains("access") || p.contains("grant"))) {
            return new AICommandGeneration(prompt, "termux-setup-storage",
                "Requests Android storage runtime permission and creates symlinks in ~/storage to DCIM, Downloads, and internal shared storage.",
                0.98f, listOf("ls -la ~/storage", "termux-info"), AICommandExplanation.RiskLevel.SAFE);
        }

        if (p.contains("clipboard") || p.contains("copy to clip") || p.contains("copy clipboard")) {
            return new AICommandGeneration(prompt, "termux-clipboard-set 'Copied text here'",
                "Copies the specified text directly to the Android system clipboard.",
                0.95f, listOf("termux-clipboard-get", "echo 'text' | termux-clipboard-set"), AICommandExplanation.RiskLevel.SAFE);
        }

        if (p.contains("python venv") || p.contains("virtual environment") || (p.contains("create") && p.contains("venv"))) {
            return new AICommandGeneration(prompt, "python3 -m venv venv && source venv/bin/activate",
                "Creates an isolated Python 3 virtual environment in the 'venv' directory and activates it in the current shell.",
                0.96f, listOf("source venv/bin/activate", "deactivate"), AICommandExplanation.RiskLevel.SAFE);
        }

        if (p.contains("ping") || p.contains("check internet") || p.contains("test connection") || p.contains("connectivity")) {
            return new AICommandGeneration(prompt, "ping -c 4 1.1.1.1",
                "Sends 4 ICMP ping packets to Cloudflare public DNS (1.1.1.1) to test internet connectivity and packet latency.",
                0.95f, listOf("ping -c 4 8.8.8.8", "curl -Iv https://1.1.1.1"), AICommandExplanation.RiskLevel.SAFE);
        }

        if (p.contains("open ports") || p.contains("listening ports") || p.contains("check ports")) {
            return new AICommandGeneration(prompt, "ss -tulnp",
                "Displays all currently open and listening TCP and UDP sockets along with the process names and PIDs bound to them.",
                0.94f, listOf("netstat -tulnp", "lsof -i -P -n | grep LISTEN"), AICommandExplanation.RiskLevel.SAFE);
        }

        if (p.contains("large file") || (p.contains("find") && p.contains("size")) || p.contains("over 50mb") || p.contains("over 100mb")) {
            return new AICommandGeneration(prompt, "find . -type f -size +100M -exec ls -lh {} + | sort -k 5 -hr",
                "Finds all files larger than 100MB in the current directory tree and sorts them in descending order of size.",
                0.95f, listOf("du -ah . | sort -rh | head -n 20", "find /sdcard -size +50M"), AICommandExplanation.RiskLevel.SAFE);
        }

        if (p.contains("kill port") || (p.contains("port") && p.contains("kill")) || (p.contains("process") && p.contains("port"))) {
            Matcher m = Pattern.compile("\\b(\\d{2,5})\\b").matcher(p);
            String port = m.find() ? m.group(1) : "8080";
            return new AICommandGeneration(prompt, "kill -9 $(lsof -t -i:" + port + ")",
                "Finds the process PID listening on port " + port + " and terminates it immediately.",
                0.92f, listOf("fuser -k " + port + "/tcp", "netstat -tulnp | grep :" + port), AICommandExplanation.RiskLevel.CAUTION);
        }

        if (p.contains("extract") || p.contains("unzip") || p.contains("untar") || p.contains("tar.gz")) {
            return new AICommandGeneration(prompt, "tar -xzvf archive.tar.gz",
                "Extracts a gzip-compressed tarball archive with verbose file listing.",
                0.90f, listOf("unzip archive.zip", "tar -xvf archive.tar.xz"), AICommandExplanation.RiskLevel.SAFE);
        }

        if (p.contains("compress") || p.contains("create tar") || p.contains("zip folder")) {
            return new AICommandGeneration(prompt, "tar -czvf archive.tar.gz directory_to_compress/",
                "Creates a gzip-compressed tar archive containing the specified directory.",
                0.90f, listOf("zip -r archive.zip folder/", "tar -cJvf archive.tar.xz folder/"), AICommandExplanation.RiskLevel.SAFE);
        }

        if (p.contains("reverse ssh") || (p.contains("ssh") && p.contains("tunnel")) || (p.contains("forward") && p.contains("port"))) {
            return new AICommandGeneration(prompt, "ssh -L 8080:localhost:8080 -N -f user@remote_server",
                "Establishes an SSH tunnel forwarding local port 8080 to remote port 8080 in the background.",
                0.88f, listOf("ssh -R 9000:localhost:3000 user@remote_server", "autossh -M 0 -L 8080:localhost:8080 user@remote"), AICommandExplanation.RiskLevel.SAFE);
        }

        if (p.contains("disk space") || p.contains("storage") || p.contains("free space")) {
            return new AICommandGeneration(prompt, "df -h && du -sh * | sort -hr | head -n 10",
                "Displays overall disk filesystem statistics and lists the top 10 largest items in the current directory.",
                0.95f, listOf("df -Th", "ncdu ."), AICommandExplanation.RiskLevel.SAFE);
        }

        if (p.contains("git undo") || p.contains("undo commit") || p.contains("revert commit")) {
            return new AICommandGeneration(prompt, "git reset --soft HEAD~1",
                "Undoes the most recent commit while preserving all changed files in the staging area.",
                0.93f, listOf("git reset --hard HEAD~1 (Warning: Discards changes)", "git restore --staged ."), AICommandExplanation.RiskLevel.CAUTION);
        }

        if (p.contains("git branch") || p.contains("new branch") || p.contains("create branch")) {
            return new AICommandGeneration(prompt, "git checkout -b feature/my-feature",
                "Creates and switches immediately to a new Git branch named feature/my-feature.",
                0.94f, listOf("git switch -c feature/my-feature", "git branch -a"), AICommandExplanation.RiskLevel.SAFE);
        }

        if (p.contains("git stash") || p.contains("save changes")) {
            return new AICommandGeneration(prompt, "git stash push -m 'WIP temporary stash'",
                "Saves uncommitted local changes to the stash stack with a descriptive message.",
                0.95f, listOf("git stash pop", "git stash list"), AICommandExplanation.RiskLevel.SAFE);
        }

        if (p.contains("docker prune") || (p.contains("docker") && p.contains("clean"))) {
            return new AICommandGeneration(prompt, "docker system prune -af --volumes",
                "Removes all unused Docker containers, networks, images, and anonymous volumes.",
                0.90f, listOf("docker container prune", "docker image prune -a"), AICommandExplanation.RiskLevel.CAUTION);
        }

        if (p.contains("ip address") || p.contains("my ip") || p.contains("network ip")) {
            return new AICommandGeneration(prompt, "curl -s https://ifconfig.me && ip -br addr",
                "Retrieves your public IP address and lists all local network interface IP assignments.",
                0.92f, listOf("ifconfig", "ip route get 1.1.1.1"), AICommandExplanation.RiskLevel.SAFE);
        }

        if (p.contains("search text") || p.contains("grep") || (p.contains("find") && p.contains("word"))) {
            return new AICommandGeneration(prompt, "grep -rnI 'SEARCH_TERM' .",
                "Recursively searches for SEARCH_TERM in current directory, showing line numbers and skipping binary files.",
                0.94f, listOf("grep -i 'term' file.txt", "find . -type f -exec grep -H 'term' {} +"), AICommandExplanation.RiskLevel.SAFE);
        }

        if (p.contains("update") || p.contains("upgrade") || p.contains("termux update")) {
            return new AICommandGeneration(prompt, "pkg update && pkg upgrade -y",
                "Updates package repository indexes and upgrades all installed Termux packages.",
                0.98f, listOf("apt update && apt upgrade -y"), AICommandExplanation.RiskLevel.SAFE);
        }

        // Generic fallback
        return new AICommandGeneration(prompt, "echo 'Generated command for: " + prompt.replace("'", "") + "'",
            "Custom command generated from prompt: " + prompt,
            0.70f, listOf("help", "man bash"), AICommandExplanation.RiskLevel.SAFE);
    }

    @Nullable
    private static String evaluateDestructiveRisk(@NonNull String command) {
        String c = command.toLowerCase(Locale.ROOT).replaceAll("\\s+", " ");
        if (c.contains("rm -rf /") || c.contains("rm -fr /") || c.contains("rm -rf /*") || c.contains("rm -r -f /")) {
            return "CRITICAL DANGER: Attempting to delete root filesystem (/). This will destroy the entire OS/container!";
        }
        if (c.contains("rm -rf ~") || c.contains("rm -rf $home") || c.contains("rm -rf *") || c.contains("rm -rf .")) {
            return "HIGH DANGER: Deleting entire home directory or current directory files recursively without confirmation.";
        }
        if (c.contains(":(){ :|:& };:") || c.contains("fork bomb")) {
            return "CRITICAL DANGER: Fork bomb detected. This will exhaust all system process table entries and freeze the device!";
        }
        if (c.contains("mkfs.") || c.contains("dd if=/dev/zero") || c.contains("dd if=/dev/urandom") || c.contains("> /dev/sd") || c.contains("> /dev/block")) {
            return "DESTRUCTIVE WARNING: Direct disk write or format detected. This may overwrite raw storage partitions!";
        }
        if (c.contains("chmod -r 777 /") || c.contains("chmod 777 /")) {
            return "SECURITY RISK: Making root filesystem world-writable compromises application sandboxing.";
        }
        if ((c.contains("curl ") || c.contains("wget ")) && (c.contains("| sh") || c.contains("| bash") || c.contains("| zsh"))) {
            return "CAUTION: Piping unverified remote internet content directly into a shell interpreter poses significant security risks.";
        }
        return null;
    }

    private static class CommandMetadata {
        final String mBinary;
        final String mSummary;
        final Map<String, String> mFlags;
        final List<String> mExamples;
        final AICommandExplanation.RiskLevel mDefaultRisk;

        CommandMetadata(String binary, String summary, Map<String, String> flags, List<String> examples, AICommandExplanation.RiskLevel defaultRisk) {
            this.mBinary = binary;
            this.mSummary = summary;
            this.mFlags = flags;
            this.mExamples = examples;
            this.mDefaultRisk = defaultRisk;
        }
    }
}
